version: '3.9'
services:
  backend:
    build: ../backend
    working_dir: /app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:////app/app.db
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - ../backend:/app
  frontend:
    build: ../frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=http://localhost:8000
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    volumes:
      - ../frontend:/usr/src/app
