name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  move-tests:
    name: Move tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies for Sui CLI
        run: sudo apt-get update && sudo apt-get install -y libssl-dev libpq-dev curl git
      - name: Install Sui CLI
        run: |
          set -e
          curl -L https://github.com/MystenLabs/sui/releases/latest/download/sui -o sui
          chmod +x sui
          sudo mv sui /usr/local/bin/sui
          sui --version
      - name: Run Move tests
        working-directory: sui-loyal/sui-packages/Loyalty
        run: sui move test

  backend:
    name: Backend tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Python deps
        working-directory: sui-loyal/backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pytest
        working-directory: sui-loyal/backend
        run: pytest -q

  frontend:
    name: Frontend tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'sui-loyal/frontend/package-lock.json'
      - name: Install deps
        working-directory: sui-loyal/frontend
        run: npm ci || npm install
      - name: Run unit tests
        working-directory: sui-loyal/frontend
        run: npm test -- --run
